/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'
import { Route as DashboardStudentRouteImport } from './routes/dashboard.student'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as ApiPublicAvatarRouteImport } from './routes/api/public/avatar'
import { Route as ApiPublicMaterialRouteImport } from './routes/api/public/material'
import { Route as ApiTeacherSettingsRouteImport } from './routes/api/teacher/settings'
import { Route as DashboardAdminIndexRouteImport } from './routes/dashboard.admin.index'
import { Route as DashboardAdminAnnouncementsRouteImport } from './routes/dashboard.admin.announcements'
import { Route as DashboardAdminAttendanceRouteImport } from './routes/dashboard.admin.attendance'
import { Route as DashboardAdminCoursesRouteImport } from './routes/dashboard.admin.courses'
import { Route as DashboardAdminGradesRouteImport } from './routes/dashboard.admin.grades'
import { Route as DashboardAdminSettingsRouteImport } from './routes/dashboard.admin.settings'
import { Route as DashboardAdminStudentsRouteImport } from './routes/dashboard.admin.students'
import { Route as DashboardAdminTeachersRouteImport } from './routes/dashboard.admin.teachers'
import { Route as DashboardStudentIndexRouteImport } from './routes/dashboard.student.index'
import { Route as DashboardStudentAssignmentsRouteImport } from './routes/dashboard.student.assignments'
import { Route as DashboardStudentAttendanceRouteImport } from './routes/dashboard.student.attendance'
import { Route as DashboardStudentGradesRouteImport } from './routes/dashboard.student.grades'
import { Route as DashboardStudentQuizzesRouteImport } from './routes/dashboard.student.quizzes'
import { Route as DashboardStudentSettingsRouteImport } from './routes/dashboard.student.settings'
import { Route as DashboardTeacherSettingsRouteImport } from './routes/dashboard.teacher.settings'
import { Route as ApiPublicHardwareAttendanceRouteImport } from './routes/api/public/hardware/attendance'
import { Route as ApiPublicHardwareSyncUsersRouteImport } from './routes/api/public/hardware/sync-users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/dashboard/admin',
  path: '/dashboard/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardStudentRoute = DashboardStudentRouteImport.update({
  id: '/dashboard/student',
  path: '/dashboard/student',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAvatarRoute = ApiPublicAvatarRouteImport.update({
  id: '/api/public/avatar',
  path: '/api/public/avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMaterialRoute = ApiPublicMaterialRouteImport.update({
  id: '/api/public/material',
  path: '/api/public/material',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTeacherSettingsRoute = ApiTeacherSettingsRouteImport.update({
  id: '/api/teacher/settings',
  path: '/api/teacher/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminAnnouncementsRoute =
  DashboardAdminAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminAttendanceRoute =
  DashboardAdminAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminCoursesRoute = DashboardAdminCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminGradesRoute = DashboardAdminGradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminSettingsRoute = DashboardAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminStudentsRoute = DashboardAdminStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminTeachersRoute = DashboardAdminTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardStudentIndexRoute = DashboardStudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardStudentRoute,
} as any)
const DashboardStudentAssignmentsRoute =
  DashboardStudentAssignmentsRouteImport.update({
    id: '/assignments',
    path: '/assignments',
    getParentRoute: () => DashboardStudentRoute,
  } as any)
const DashboardStudentAttendanceRoute =
  DashboardStudentAttendanceRouteImport.update({
    id: '/attendance',
    path: '/attendance',
    getParentRoute: () => DashboardStudentRoute,
  } as any)
const DashboardStudentGradesRoute = DashboardStudentGradesRouteImport.update({
  id: '/grades',
  path: '/grades',
  getParentRoute: () => DashboardStudentRoute,
} as any)
const DashboardStudentQuizzesRoute = DashboardStudentQuizzesRouteImport.update({
  id: '/quizzes',
  path: '/quizzes',
  getParentRoute: () => DashboardStudentRoute,
} as any)
const DashboardStudentSettingsRoute =
  DashboardStudentSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardStudentRoute,
  } as any)
const DashboardTeacherSettingsRoute =
  DashboardTeacherSettingsRouteImport.update({
    id: '/dashboard/teacher/settings',
    path: '/dashboard/teacher/settings',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHardwareAttendanceRoute =
  ApiPublicHardwareAttendanceRouteImport.update({
    id: '/api/public/hardware/attendance',
    path: '/api/public/hardware/attendance',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHardwareSyncUsersRoute =
  ApiPublicHardwareSyncUsersRouteImport.update({
    id: '/api/public/hardware/sync-users',
    path: '/api/public/hardware/sync-users',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/chat': typeof ApiChatRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/student': typeof DashboardStudentRouteWithChildren
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/avatar': typeof ApiPublicAvatarRoute
  '/api/public/material': typeof ApiPublicMaterialRoute
  '/api/teacher/settings': typeof ApiTeacherSettingsRoute
  '/dashboard/admin/announcements': typeof DashboardAdminAnnouncementsRoute
  '/dashboard/admin/attendance': typeof DashboardAdminAttendanceRoute
  '/dashboard/admin/courses': typeof DashboardAdminCoursesRoute
  '/dashboard/admin/grades': typeof DashboardAdminGradesRoute
  '/dashboard/admin/settings': typeof DashboardAdminSettingsRoute
  '/dashboard/admin/students': typeof DashboardAdminStudentsRoute
  '/dashboard/admin/teachers': typeof DashboardAdminTeachersRoute
  '/dashboard/student/assignments': typeof DashboardStudentAssignmentsRoute
  '/dashboard/student/attendance': typeof DashboardStudentAttendanceRoute
  '/dashboard/student/grades': typeof DashboardStudentGradesRoute
  '/dashboard/student/quizzes': typeof DashboardStudentQuizzesRoute
  '/dashboard/student/settings': typeof DashboardStudentSettingsRoute
  '/dashboard/teacher/settings': typeof DashboardTeacherSettingsRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/student/': typeof DashboardStudentIndexRoute
  '/api/public/hardware/attendance': typeof ApiPublicHardwareAttendanceRoute
  '/api/public/hardware/sync-users': typeof ApiPublicHardwareSyncUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/chat': typeof ApiChatRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/avatar': typeof ApiPublicAvatarRoute
  '/api/public/material': typeof ApiPublicMaterialRoute
  '/api/teacher/settings': typeof ApiTeacherSettingsRoute
  '/dashboard/admin/announcements': typeof DashboardAdminAnnouncementsRoute
  '/dashboard/admin/attendance': typeof DashboardAdminAttendanceRoute
  '/dashboard/admin/courses': typeof DashboardAdminCoursesRoute
  '/dashboard/admin/grades': typeof DashboardAdminGradesRoute
  '/dashboard/admin/settings': typeof DashboardAdminSettingsRoute
  '/dashboard/admin/students': typeof DashboardAdminStudentsRoute
  '/dashboard/admin/teachers': typeof DashboardAdminTeachersRoute
  '/dashboard/student/assignments': typeof DashboardStudentAssignmentsRoute
  '/dashboard/student/attendance': typeof DashboardStudentAttendanceRoute
  '/dashboard/student/grades': typeof DashboardStudentGradesRoute
  '/dashboard/student/quizzes': typeof DashboardStudentQuizzesRoute
  '/dashboard/student/settings': typeof DashboardStudentSettingsRoute
  '/dashboard/teacher/settings': typeof DashboardTeacherSettingsRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
  '/dashboard/student': typeof DashboardStudentIndexRoute
  '/api/public/hardware/attendance': typeof ApiPublicHardwareAttendanceRoute
  '/api/public/hardware/sync-users': typeof ApiPublicHardwareSyncUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/mcp': typeof McpRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/api/chat': typeof ApiChatRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/student': typeof DashboardStudentRouteWithChildren
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/avatar': typeof ApiPublicAvatarRoute
  '/api/public/material': typeof ApiPublicMaterialRoute
  '/api/teacher/settings': typeof ApiTeacherSettingsRoute
  '/dashboard/admin/announcements': typeof DashboardAdminAnnouncementsRoute
  '/dashboard/admin/attendance': typeof DashboardAdminAttendanceRoute
  '/dashboard/admin/courses': typeof DashboardAdminCoursesRoute
  '/dashboard/admin/grades': typeof DashboardAdminGradesRoute
  '/dashboard/admin/settings': typeof DashboardAdminSettingsRoute
  '/dashboard/admin/students': typeof DashboardAdminStudentsRoute
  '/dashboard/admin/teachers': typeof DashboardAdminTeachersRoute
  '/dashboard/student/assignments': typeof DashboardStudentAssignmentsRoute
  '/dashboard/student/attendance': typeof DashboardStudentAttendanceRoute
  '/dashboard/student/grades': typeof DashboardStudentGradesRoute
  '/dashboard/student/quizzes': typeof DashboardStudentQuizzesRoute
  '/dashboard/student/settings': typeof DashboardStudentSettingsRoute
  '/dashboard/teacher/settings': typeof DashboardTeacherSettingsRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/student/': typeof DashboardStudentIndexRoute
  '/api/public/hardware/attendance': typeof ApiPublicHardwareAttendanceRoute
  '/api/public/hardware/sync-users': typeof ApiPublicHardwareSyncUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/mcp'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/chat'
    | '/dashboard/admin'
    | '/dashboard/student'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/avatar'
    | '/api/public/material'
    | '/api/teacher/settings'
    | '/dashboard/admin/announcements'
    | '/dashboard/admin/attendance'
    | '/dashboard/admin/courses'
    | '/dashboard/admin/grades'
    | '/dashboard/admin/settings'
    | '/dashboard/admin/students'
    | '/dashboard/admin/teachers'
    | '/dashboard/student/assignments'
    | '/dashboard/student/attendance'
    | '/dashboard/student/grades'
    | '/dashboard/student/quizzes'
    | '/dashboard/student/settings'
    | '/dashboard/teacher/settings'
    | '/dashboard/admin/'
    | '/dashboard/student/'
    | '/api/public/hardware/attendance'
    | '/api/public/hardware/sync-users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/mcp'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/chat'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/avatar'
    | '/api/public/material'
    | '/api/teacher/settings'
    | '/dashboard/admin/announcements'
    | '/dashboard/admin/attendance'
    | '/dashboard/admin/courses'
    | '/dashboard/admin/grades'
    | '/dashboard/admin/settings'
    | '/dashboard/admin/students'
    | '/dashboard/admin/teachers'
    | '/dashboard/student/assignments'
    | '/dashboard/student/attendance'
    | '/dashboard/student/grades'
    | '/dashboard/student/quizzes'
    | '/dashboard/student/settings'
    | '/dashboard/teacher/settings'
    | '/dashboard/admin'
    | '/dashboard/student'
    | '/api/public/hardware/attendance'
    | '/api/public/hardware/sync-users'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/mcp'
    | '/sitemap.xml'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/api/chat'
    | '/dashboard/admin'
    | '/dashboard/student'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/avatar'
    | '/api/public/material'
    | '/api/teacher/settings'
    | '/dashboard/admin/announcements'
    | '/dashboard/admin/attendance'
    | '/dashboard/admin/courses'
    | '/dashboard/admin/grades'
    | '/dashboard/admin/settings'
    | '/dashboard/admin/students'
    | '/dashboard/admin/teachers'
    | '/dashboard/student/assignments'
    | '/dashboard/student/attendance'
    | '/dashboard/student/grades'
    | '/dashboard/student/quizzes'
    | '/dashboard/student/settings'
    | '/dashboard/teacher/settings'
    | '/dashboard/admin/'
    | '/dashboard/student/'
    | '/api/public/hardware/attendance'
    | '/api/public/hardware/sync-users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  McpRoute: typeof McpRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ApiChatRoute: typeof ApiChatRoute
  DashboardAdminRoute: typeof DashboardAdminRouteWithChildren
  DashboardStudentRoute: typeof DashboardStudentRouteWithChildren
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicAvatarRoute: typeof ApiPublicAvatarRoute
  ApiPublicMaterialRoute: typeof ApiPublicMaterialRoute
  ApiTeacherSettingsRoute: typeof ApiTeacherSettingsRoute
  DashboardTeacherSettingsRoute: typeof DashboardTeacherSettingsRoute
  ApiPublicHardwareAttendanceRoute: typeof ApiPublicHardwareAttendanceRoute
  ApiPublicHardwareSyncUsersRoute: typeof ApiPublicHardwareSyncUsersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/student': {
      id: '/dashboard/student'
      path: '/dashboard/student'
      fullPath: '/dashboard/student'
      preLoaderRoute: typeof DashboardStudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/avatar': {
      id: '/api/public/avatar'
      path: '/api/public/avatar'
      fullPath: '/api/public/avatar'
      preLoaderRoute: typeof ApiPublicAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/material': {
      id: '/api/public/material'
      path: '/api/public/material'
      fullPath: '/api/public/material'
      preLoaderRoute: typeof ApiPublicMaterialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/teacher/settings': {
      id: '/api/teacher/settings'
      path: '/api/teacher/settings'
      fullPath: '/api/teacher/settings'
      preLoaderRoute: typeof ApiTeacherSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin/': {
      id: '/dashboard/admin/'
      path: '/'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/announcements': {
      id: '/dashboard/admin/announcements'
      path: '/announcements'
      fullPath: '/dashboard/admin/announcements'
      preLoaderRoute: typeof DashboardAdminAnnouncementsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/attendance': {
      id: '/dashboard/admin/attendance'
      path: '/attendance'
      fullPath: '/dashboard/admin/attendance'
      preLoaderRoute: typeof DashboardAdminAttendanceRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/courses': {
      id: '/dashboard/admin/courses'
      path: '/courses'
      fullPath: '/dashboard/admin/courses'
      preLoaderRoute: typeof DashboardAdminCoursesRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/grades': {
      id: '/dashboard/admin/grades'
      path: '/grades'
      fullPath: '/dashboard/admin/grades'
      preLoaderRoute: typeof DashboardAdminGradesRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/settings': {
      id: '/dashboard/admin/settings'
      path: '/settings'
      fullPath: '/dashboard/admin/settings'
      preLoaderRoute: typeof DashboardAdminSettingsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/students': {
      id: '/dashboard/admin/students'
      path: '/students'
      fullPath: '/dashboard/admin/students'
      preLoaderRoute: typeof DashboardAdminStudentsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/teachers': {
      id: '/dashboard/admin/teachers'
      path: '/teachers'
      fullPath: '/dashboard/admin/teachers'
      preLoaderRoute: typeof DashboardAdminTeachersRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/student/': {
      id: '/dashboard/student/'
      path: '/'
      fullPath: '/dashboard/student/'
      preLoaderRoute: typeof DashboardStudentIndexRouteImport
      parentRoute: typeof DashboardStudentRoute
    }
    '/dashboard/student/assignments': {
      id: '/dashboard/student/assignments'
      path: '/assignments'
      fullPath: '/dashboard/student/assignments'
      preLoaderRoute: typeof DashboardStudentAssignmentsRouteImport
      parentRoute: typeof DashboardStudentRoute
    }
    '/dashboard/student/attendance': {
      id: '/dashboard/student/attendance'
      path: '/attendance'
      fullPath: '/dashboard/student/attendance'
      preLoaderRoute: typeof DashboardStudentAttendanceRouteImport
      parentRoute: typeof DashboardStudentRoute
    }
    '/dashboard/student/grades': {
      id: '/dashboard/student/grades'
      path: '/grades'
      fullPath: '/dashboard/student/grades'
      preLoaderRoute: typeof DashboardStudentGradesRouteImport
      parentRoute: typeof DashboardStudentRoute
    }
    '/dashboard/student/quizzes': {
      id: '/dashboard/student/quizzes'
      path: '/quizzes'
      fullPath: '/dashboard/student/quizzes'
      preLoaderRoute: typeof DashboardStudentQuizzesRouteImport
      parentRoute: typeof DashboardStudentRoute
    }
    '/dashboard/student/settings': {
      id: '/dashboard/student/settings'
      path: '/settings'
      fullPath: '/dashboard/student/settings'
      preLoaderRoute: typeof DashboardStudentSettingsRouteImport
      parentRoute: typeof DashboardStudentRoute
    }
    '/dashboard/teacher/settings': {
      id: '/dashboard/teacher/settings'
      path: '/dashboard/teacher/settings'
      fullPath: '/dashboard/teacher/settings'
      preLoaderRoute: typeof DashboardTeacherSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hardware/attendance': {
      id: '/api/public/hardware/attendance'
      path: '/api/public/hardware/attendance'
      fullPath: '/api/public/hardware/attendance'
      preLoaderRoute: typeof ApiPublicHardwareAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hardware/sync-users': {
      id: '/api/public/hardware/sync-users'
      path: '/api/public/hardware/sync-users'
      fullPath: '/api/public/hardware/sync-users'
      preLoaderRoute: typeof ApiPublicHardwareSyncUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardAdminRouteChildren {
  DashboardAdminAnnouncementsRoute: typeof DashboardAdminAnnouncementsRoute
  DashboardAdminAttendanceRoute: typeof DashboardAdminAttendanceRoute
  DashboardAdminCoursesRoute: typeof DashboardAdminCoursesRoute
  DashboardAdminGradesRoute: typeof DashboardAdminGradesRoute
  DashboardAdminSettingsRoute: typeof DashboardAdminSettingsRoute
  DashboardAdminStudentsRoute: typeof DashboardAdminStudentsRoute
  DashboardAdminTeachersRoute: typeof DashboardAdminTeachersRoute
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
}

const DashboardAdminRouteChildren: DashboardAdminRouteChildren = {
  DashboardAdminAnnouncementsRoute: DashboardAdminAnnouncementsRoute,
  DashboardAdminAttendanceRoute: DashboardAdminAttendanceRoute,
  DashboardAdminCoursesRoute: DashboardAdminCoursesRoute,
  DashboardAdminGradesRoute: DashboardAdminGradesRoute,
  DashboardAdminSettingsRoute: DashboardAdminSettingsRoute,
  DashboardAdminStudentsRoute: DashboardAdminStudentsRoute,
  DashboardAdminTeachersRoute: DashboardAdminTeachersRoute,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
}

const DashboardAdminRouteWithChildren = DashboardAdminRoute._addFileChildren(
  DashboardAdminRouteChildren,
)

interface DashboardStudentRouteChildren {
  DashboardStudentAssignmentsRoute: typeof DashboardStudentAssignmentsRoute
  DashboardStudentAttendanceRoute: typeof DashboardStudentAttendanceRoute
  DashboardStudentGradesRoute: typeof DashboardStudentGradesRoute
  DashboardStudentQuizzesRoute: typeof DashboardStudentQuizzesRoute
  DashboardStudentSettingsRoute: typeof DashboardStudentSettingsRoute
  DashboardStudentIndexRoute: typeof DashboardStudentIndexRoute
}

const DashboardStudentRouteChildren: DashboardStudentRouteChildren = {
  DashboardStudentAssignmentsRoute: DashboardStudentAssignmentsRoute,
  DashboardStudentAttendanceRoute: DashboardStudentAttendanceRoute,
  DashboardStudentGradesRoute: DashboardStudentGradesRoute,
  DashboardStudentQuizzesRoute: DashboardStudentQuizzesRoute,
  DashboardStudentSettingsRoute: DashboardStudentSettingsRoute,
  DashboardStudentIndexRoute: DashboardStudentIndexRoute,
}

const DashboardStudentRouteWithChildren =
  DashboardStudentRoute._addFileChildren(DashboardStudentRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  McpRoute: McpRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ApiChatRoute: ApiChatRoute,
  DashboardAdminRoute: DashboardAdminRouteWithChildren,
  DashboardStudentRoute: DashboardStudentRouteWithChildren,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicAvatarRoute: ApiPublicAvatarRoute,
  ApiPublicMaterialRoute: ApiPublicMaterialRoute,
  ApiTeacherSettingsRoute: ApiTeacherSettingsRoute,
  DashboardTeacherSettingsRoute: DashboardTeacherSettingsRoute,
  ApiPublicHardwareAttendanceRoute: ApiPublicHardwareAttendanceRoute,
  ApiPublicHardwareSyncUsersRoute: ApiPublicHardwareSyncUsersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
